services:
  fastapi:
    build:
      context: .
    container_name: fastapi-book-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db  # Using SQLite as file-based DB
    volumes:
      - ./test.db:/app/test.db  # Mount the SQLite database file into the container

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount Nginx configuration file
    depends_on:
      - fastapi  # Wait for FastAPI before starting Nginx
    links:
      - fastapi
