version: '3.8'

services:
  fastapi:
    build:
      context: .
    container_name: fastapi-book-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///./test.db  # Replace with your actual DB URL if needed

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    links:
      - fastapi
