name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Check if the repo exists, if not clone it
            if [ ! -d "/home/ubuntu/your-fastapi-repo" ]; then
              echo "Repository not found, cloning..."
              git clone https://github.com/yourusername/your-repo.git /home/ubuntu/your-fastapi-repo
            fi
            
            cd /home/ubuntu/your-fastapi-repo || exit
            git pull origin main || exit

            # Ensure venv exists and activate it
            if [ ! -d "venv" ]; then
              echo "Virtual environment not found. Creating it..."
              python3 -m venv venv
            fi
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Restart the service (e.g., FastAPI)
            sudo systemctl restart fastapi || exit

            echo "Deployment successful!"
          EOF
