name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key for EC2 access
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          cp private_key.pem ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add GitHub to known hosts (to prevent SSH warnings)
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up SSH key for GitHub access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/github_id_rsa
          chmod 600 ~/.ssh/github_id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Ensure repository exists on the EC2 instance
            if [ ! -d "/home/ubuntu/your-fastapi-repo" ]; then
              echo "Repository not found, cloning..."
              git clone git@github.com:Payne680/fastapi-book-project.git /home/ubuntu/fastapi-book-project
            fi

            cd /home/ubuntu/fastapi-book-project || exit
            git pull origin main || exit

            # Ensure virtual environment exists and activate it
            if [ ! -d "venv" ]; then
              echo "Virtual environment not found. Creating it..."
              python3 -m venv venv
            fi
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Restart FastAPI service
            sudo systemctl restart fastapi || exit

            echo "Deployment successful!"
          EOF
